# Podstawy Obliczeń Komputerowych
## Metody rozwiązywania układów równań liniowych
### laboratorium II

1. Wyznaczenie liczby rozwiązań układu 

***twierdzenie Kroneckera - Capellego*** 

In [3]:
import numpy as np

A = np.array([[2., 1., 1., -1.], 
             [1., 1., -1., 1.], 
             [1., 1., 1., 1.,], 
             [-1., 2., -1., 1.]])

b = np.array([[3., 4., 10., 4.]])
B = np.array([3., 4., 10., 4.])

U = np.concatenate((A,b.T), axis=1)
print("Macierz U:")
print(U)

# Policzenie rządu utworzonych macierzy
rankA = np.linalg.matrix_rank(A)
rankU = np.linalg.matrix_rank(U)

# Policzenie liczby niewiadomych
n = np.shape(A)[1]

if rankA == rankU and n==rankA:
    print("Układ posiada jedno rozwiązanie")
    print("\nRozwiazanie prawidłowe:")
    x = np.linalg.solve(A,B)
    print(x)
    
elif rankA == rankU and n!=rankA:
    print(f"Układ posiada nieskończenie wiele rozwiązań zależnych od {n} parametrów")
elif rankA != rankU:
    print("Układ jest sprzeczny")
    print("KONIEC PROGRAMU")   
    

Macierz U:
[[ 2.  1.  1. -1.  3.]
 [ 1.  1. -1.  1.  4.]
 [ 1.  1.  1.  1. 10.]
 [-1.  2. -1.  1.  4.]]
Układ posiada jedno rozwiązanie

Rozwiazanie prawidłowe:
[1. 2. 3. 4.]


2. Wyznaczenie rozwiązania układu równań metodą skończoną

***Eliminacja Gaussa***

In [3]:
# import wymaganych bibliotek
import numpy as np
import sys

# Wczytanie liczby niewiadomych
n = int(input('Wprowadź liczbę niewiadomych: '))

# Utworzenie macierzy rozszerzonej U
U = np.zeros((n,n+1))

# Utworzenie wektora rozwiązań
x = np.zeros(n)

# Wprowadzenie elementów macierzy U
print("Podaj poszczególne elementy macierzy roszerzonej")
for i in range(n):
    for j in range(n+1):
        U[i][j] = float(input( f"U[{i+1}][{j+1}]= "))

# Podgląd wczytanej macierzy U
print("\nU:")
print(U)

# Algorytm Eliminacji Gaussa
for i in range(n):
    if U[i][i] == 0.0:
        sys.exit("Wykryto dzielenie przez 0")
        
    for j in range(i+1, n):
        ratio = U[j][i]/U[i][i]
        
        for k in range(n+1):
            U[j][k] = U[j][k] - ratio * U[i][k]

# Podstawienie odwrotne
x[n-1] = U[n-1][n]/U[n-1][n-1]

for i in range(n-2,-1,-1):
    x[i] = U[i][n]
    
    for j in range(i+1,n):
        x[i] = x[i] - U[i][j]*x[j]
    
    x[i] = x[i]/U[i][i]

# Wyświetlenie wektora rozwiązań
print('\nRozwiązanie układu: ')
for i in range(n):
    print(f"x{i}={x[i]}", end="\t")

Podaj poszczególne elementy macierzy roszerzonej

U:
[[ 2.  1.  1. -1.  3.]
 [ 1.  1. -1.  1.  4.]
 [ 1.  1.  1.  1. 10.]
 [-1.  2. -1.  1.  4.]]

Rozwiązanie układu: 
x0=1.0	x1=2.0	x2=3.0	x3=4.0	

3. Wyznaczenie rozwiązania układu równań metodą iteracyjną

***Metoda Gaussa-Seidela***

- Sprawdzenie czy badany układ równań posiada macierz A przekątniowo dominującą 

In [2]:
import numpy as np

A = np.array([[2., 1., 1., -1.], 
             [1., 1., -1., 1.], 
             [1., 1., 1., 1.,], 
             [-1., 2., -1., 1.]])

b = np.array([3., 4., 10., 4.])


# Policz sumę wartości bezwględnych przekątnej macierzy
diag = np.diag(np.abs(A)) 

# Policz sumę wartości bezwględnych poszczególnych wierszy macierzy, a następnie odejmij od niej sumę wartości bezwględnych przekątnej
off_diag = np.sum(np.abs(A), axis=1) - diag 

# Sprawdzenie czy macierz A jest przekątniowo dominująca
if np.all(diag > off_diag):
    print("Macierz jest przekątniowo dominująca")
else:
    print("Macierz NIE jest przekątniowo dominująca")


Macierz NIE jest przekątniowo dominująca


- Użycie metody ***GS*** 
    - dla macierzy A przekątniowo dominującej

In [5]:
import numpy as np

ITERATION_LIMIT = 1000

# Inicjalizacja macierzy A
A = np.array([[10., -1., 2., 0.],
              [-1., 11., -1., 3.],
              [2., -1., 10., -1.],
              [0., 3., -1., 8.]])
# Inicjalizacja wektora b
b = np.array([6.0, 25.0, -11.0, 15.0])

print("Wygląd układu równań:")
for i in range(A.shape[0]):
    print(A[i], b[i])

B = np.array([[6.0, 25.0, -11.0, 15.0]])
U = np.concatenate((A,B.T), axis=1)

# Policzenie rządu utworzonych macierzy
rankA = np.linalg.matrix_rank(A)
rankU = np.linalg.matrix_rank(U)

# Policzenie liczby niewiadomych
n = np.shape(A)[1]

if rankA == rankU and n==rankA:
    print("Układ posiada jedno rozwiązanie")
    print("\nRozwiazanie prawidłowe:")
    x = np.linalg.solve(A,b)
    print(x)
    
elif rankA == rankU and n!=rankA:
    print(f"Układ posiada nieskończenie wiele rozwiązań zależnych od {n} parametrów")
elif rankA != rankU:
    print("Układ jest sprzeczny")

# Policz sumę wartości bezwględnych przekątnej macierzy
diag = np.diag(np.abs(A)) 

# Policz sumę wartości bezwględnych poszczególnych wierszy macierzy, a następnie odejmij od niej sumę wartości bezwględnych przekątnej
off_diag = np.sum(np.abs(A), axis=1) - diag 

# Sprawdzenie czy macierz A jest przekątniowo dominująca
if np.all(diag > off_diag):
    print("Macierz jest przekątniowo dominująca")
else:
    print("Macierz NIE jest przekątniowo dominująca")

print("\nRozpoczęcie obliczeń metody:")
x = np.zeros_like(b)
for it_count in range(1, ITERATION_LIMIT):
    x_new = np.zeros_like(x)
    print(f"Iteracja {it_count}: {x}")
    for i in range(A.shape[0]):
        s1 = np.dot(A[i, :i], x_new[:i])
        s2 = np.dot(A[i, i + 1 :], x[i + 1 :])
        x_new[i] = (b[i] - s1 - s2) / A[i, i]
    if np.allclose(x, x_new, rtol=1e-8):
        break
    x = x_new

print("\nZakończenie działania programu:")
print(f"Wyniki rozwiązań: {x}")
error = np.dot(A, x) - b
print(f"Błąd: {error}")


Wygląd układu równań:
[10. -1.  2.  0.] 6.0
[-1. 11. -1.  3.] 25.0
[ 2. -1. 10. -1.] -11.0
[ 0.  3. -1.  8.] 15.0
Układ posiada jedno rozwiązanie

Rozwiazanie prawidłowe:
[ 1.  2. -1.  1.]
Macierz jest przekątniowo dominująca

Rozpoczęcie obliczeń metody:
Iteracja 1: [0. 0. 0. 0.]
Iteracja 2: [ 0.6         2.32727273 -0.98727273  0.87886364]
Iteracja 3: [ 1.03018182  2.03693802 -1.0144562   0.98434122]
Iteracja 4: [ 1.00658504  2.00355502 -1.00252738  0.99835095]
Iteracja 5: [ 1.00086098  2.00029825 -1.00030728  0.99984975]
Iteracja 6: [ 1.00009128  2.00002134 -1.00003115  0.9999881 ]
Iteracja 7: [ 1.00000836  2.00000117 -1.00000275  0.99999922]
Iteracja 8: [ 1.00000067  2.00000002 -1.00000021  0.99999996]
Iteracja 9: [ 1.00000004  1.99999999 -1.00000001  1.        ]
Iteracja 10: [ 1.  2. -1.  1.]

Zakończenie działania programu:
Wyniki rozwiązań: [ 1.  2. -1.  1.]
Błąd: [ 2.06480930e-08 -1.25551054e-08  3.61417563e-11  0.00000000e+00]
